config/routes.rb
Mastamindz::Application.routes.draw do
  root to: 'contents#home'
  match '/music',	to: 'contents#music',		via: 'get'
  match '/videos',	to: 'contents#videos',		via: 'get'
  match '/services',	to: 'contents#services',	via: 'get'
  match '/contact',	to: 'contents#contact',		via: 'get'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  def home
  end

  def music
  end

  def videos
  end

  def services
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "MastaMindz"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/contact.html.erb
<% provide(:title, 'Contact') %>

<!-- Begin style break with section title -->

<div class="row">
  <div class="large-10 columns">
    <hr>
  </div>
  <div class="large-2 columns">
    <h3>CONTACT</h3>
  </div>
</div>
  
<!-- End style break with section title -->

<!-- Begin contact info -->

<div class="row">
  <div class="large-12 columns">
    <h3>Masta Mindz LLC</h3>
  </div>
</div>

<div class="row">
  <div class="large-6 columns">
    <h4><u>PHONE</u></h4>
    <p>Kevin Lee<br>
      (516) 643-5212</p>
    <p>Istafa Marshall<br>
      (631) 579-9598</p>
  </div>
  <div class="large-6 columns">
    <h4><u>EMAIL</u></h4>
      <p>Mastamindzllc@gmail.com</p>
  </div>
</div>

<!-- End contact info -->

app/views/contents/home.html.erb
<% provide(:title, 'Home') %>
<!-- Begin style break-->

<div class="row">
  <div class="large-12 columns">
    <hr>
  </div>
</div>
  
<!-- End style break-->

<!-- Begin soundcloud message -->

<div class="row">
  <div class="small-6 columns">
    <br>
    <h4>Just a sample of what we offer...</h4>
    <br>
    <br>
  </div>
  <div class="small-6 columns"> 
  </div>
</div>

<!-- End soundcloud message -->

<!-- Begin soundcloud & twitter-->

<div class="row">
  <div class="large-6 columns">
    <div class="panel">
      <iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=http%3A%2F%2Fapi.soundcloud.com%2Fplaylists%2F5191778&amp;color=46ed2e&amp;auto_play=true&amp;show_artwork=true"></iframe>
      <p>Hear more in our <%= link_to "music", music_path %> and <%= link_to "videos", videos_path %> section</p>
    </div>  
  </div>
  <div class="large-3 columns">
    <a class="twitter-timeline"  href="https://twitter.com/MastaMindzLLC"  data-widget-id="329314091573313536">Tweets by @MastaMindzLLC</a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>      
  </div>
</div>

<!-- End soundcloud & twitter -->

app/views/contents/music.html.erb
<% provide(:title, 'Music') %>

<!-- Begin style break with section title -->

<div class="row">
  <div class="large-10 columns">
    <hr>
  </div>
  <div class="large-2 columns">
    <h3>MUSIC</h3>
  </div>
</div>
  
<!-- End style break with section title -->

<!-- Begin music section with twitter sidebar -->

  <div class="row">

    <!-- Main Blog Content -->
    <div class="large-9 columns" role="content">

      <article>

        <h4>!!!!FUTURISTICK ARCADE MUSICK!!!!</h4>

        <div class="row">
          <div class="large-9 columns">
            <iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=http%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F90662158&amp;color=46ed2e&amp;auto_play=false&amp;show_artwork=true"></iframe>
          </div>
        </div>

      </article>

      <hr />

      <article>

        <h4>Doin My Thing (Produced By MASTAMINDZLLc)</h4>

        <div class="row">
          <div class="large-9 columns">
            <iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=http%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F89235676&amp;color=46ed2e&amp;auto_play=false&amp;show_artwork=true"></iframe>
          </div>
        </div>

      </article>
      
      <hr />
      
      <article>

        <h4>!!!!DA JUGGERNAUT!!!!</h4>

        <div class="row">
          <div class="large-9 columns">
            <iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=http%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F89224552&amp;color=46ed2e&amp;auto_play=false&amp;show_artwork=true"></iframe>
          </div>
        </div>

      </article>
      
      <hr />
      
      <article>

        <h4>SPACED OUT</h4>

        <div class="row">
          <div class="large-9 columns">
            <iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=http%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F89072067&amp;color=46ed2e&amp;auto_play=false&amp;show_artwork=true"></iframe>
          </div>
        </div>

      </article>
      
      <hr />
      
      <article>

        <h4>Smart Water</h4>

        <div class="row">
          <div class="large-9 columns">
            <iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=http%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F88219809&amp;color=46ed2e&amp;auto_play=false&amp;show_artwork=true"></iframe>
          </div>
        </div>

      </article>

    </div>

    <!-- End Main Content -->


    <!-- Begin twitter sidebar -->

    <aside class="large-3 columns">

        <a class="twitter-timeline"  href="https://twitter.com/MastaMindzLLC"  data-widget-id="329314091573313536">Tweets by @MastaMindzLLC</a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

    </aside>

    <!-- End twitter sidebar -->
  </div>

<!-- End music section with twitter sidebar -->

app/views/contents/services.html.erb
<% provide(:title, 'Services') %>

<!-- Begin style break with section title -->

<div class="row">
  <div class="large-10 columns">
    <hr>
  </div>
  <div class="large-2 columns">
    <h3>SERVICES</h3>
  </div>
</div>
  
<!-- End style break with section title -->

<!-- Begin services section -->

  <div class="row">
  
    <div class="large-4 columns">
      <img src="/assets/mastamindz_beats.jpg" />
      <h4>Beats</h4>
      <p>Over 350 tracks to choose from and mixed in Pro Tools. We make custom beats TOO! Just tell us what you want and we'll make it happen!</p>
      <p><%= link_to "Contact us!", contact_path %></p>
    </div>
    
    <div class="large-4 columns">
      <img src="/assets/mastamindz_ring_tones.jpg" />
      <h4>Ring Tones</h4>
      <p>Masta Mindz created ringtones for your phone!</p>
      <p>COMING SOON!!!!!!!</p>
    </div>
    
    <div class="large-4 columns">
      <img src="/assets/mastamindz_studio_time.jpg" />
      <h4>Studio Time</h4>
      <p>Affordable studio using state of the art equipment giving you the best sound possible.</p>
      <p>COMING SOON!!!!!!!</p>
    </div>
	
    </div>
  
<!-- End services section -->

app/views/contents/videos.html.erb
<% provide(:title, 'Videos') %>

<!-- Begin style break with section title -->

<div class="row">
  <div class="large-10 columns">
    <hr>
  </div>
  <div class="large-2 columns">
    <h3>VIDEOS</h3>
  </div>
</div>
  
<!-- End style break with section title -->

<!-- Begin Video section & twitter sidebar -->

  <div class="row">

    <!-- Main Blog Content -->
    <div class="large-9 columns" role="content">

      <article>

        <h4>Cliff Clavin - Just A Warning</h4>

        <div class="row">
          <div class="large-6 columns">
            <iframe width="420" height="315" src="http://www.youtube.com/embed/MV8ac8CUjmg" frameborder="0" allowfullscreen></iframe>
          </div>
        </div>

        <p>One of our latest collaborations with Clive Clavin</p>

      </article>

    </div>

    <!-- End Main Content -->


    <!-- Sidebar -->

    <aside class="large-3 columns">

     <a class="twitter-timeline"  href="https://twitter.com/MastaMindzLLC"  data-widget-id="329314091573313536">Tweets by @MastaMindzLLC</a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

    </aside>

    <!-- End Sidebar -->
  </div>

  <!-- End Main Content and Sidebar -->

app/views/layouts/_footer.html.erb
<footer class="row">
  <div class="large-12 columns">
    <hr />
  <div class="row">
  <div class="large-6 columns">
    <p>©2013 Masta Mindz LLC</p>
  </div>
  <div class="large-3 columns">
    
  </div>
  <div class="large-3 columns">
    <a href="https://soundcloud.com/mastamindzllc" class="fc-webicon soundcloud">soundcloud</a>
    <a href="https://twitter.com/MastaMindzLLC" class="fc-webicon twitter">twitter</a>
    <a href="https://www.youtube.com/MastaMindzLLC" class="fc-webicon youtube">youtube</a>
    <a href="https://www.facebook.com/MastaMindzLLC" class="fc-webicon facebook">facebook</a>,</p>
  </div>
  </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- Begin Nav -->

<div class="row">
  <div class="large-3 columns">
    <h1><a href="https://soundcloud.com/mastamindzllc" class="fc-webicon soundcloud">soundcloud</a>
    <a href="https://twitter.com/MastaMindzLLC" class="fc-webicon twitter">twitter</a>
    <a href="https://www.youtube.com/MastaMindzLLC" class="fc-webicon youtube">youtube</a>
    <a href="https://www.facebook.com/MastaMindzLLC" class="fc-webicon facebook">facebook</a></h1>
  </div>
  <div class="large-9 columns">
    <ul class="button-group right">
      <li><%= link_to "Home",		root_path,	class: "small button"%></li>
      <li><%= link_to "Music",		music_path,	class: "small button"%></li>
      <li><%= link_to "Videos", 	videos_path,	class: "small button"%></li>
      <li><%= link_to "Services", 	services_path,	class: "small button"%></li>
      <li><%= link_to "Contact", 	contact_path, 	class: "small button"%></li>
    </ul>
  </div>
</div>

<!-- End Nav -->

<!-- Begin Masta Mindz Logo & Description-->

<div class="row">
  <div class="large-4 columns">
    <div class="panel">
	<img src="/assets/mastamindz_logo.jpg" />
    </div>
  </div>
  <div class="large-8 columns">
    <h3>Make Your Next Single Epic!</h3>
      <p>Masta Mindz LLC is a record production duo consisting of Kevin Lee "Scorpio Poizen" and Istafa Marshall "SamuraiBlack". Based out of Central Islip New York, we have a distinctive sound﻿ hyped up by alternately terse and heavy beats﻿ that can fulfill any Hip Hop, R&B or Pop artist's production needs. If you want a hit, you’d best make a call to Masta Mindz!</p>
      <p>We have over 350 tracks ready for artists of any genre. All tracks are ready to be mixed and mastered to your liking. To set up a listening session or discuss your next track <%= link_to "contact us", contact_path %>.</p>
  </div>
</div>

<!-- End Masta Mindz Logo & Description-->

app/views/layouts/_shim.html.erb
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->

<!-- Uncomment to make IE8 render like IE7 -->
<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html> 
  <head>
    <meta charset="utf-8" />
    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title><%= full_title(yield(:title)) %></title>
      <%= stylesheet_link_tag    "application" %>
      <%= javascript_include_tag "vendor/custom.modernizr" %>
      <%= csrf_meta_tags %>
      <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
      <%= yield %>
    <%= render 'layouts/footer' %>
    <%= javascript_include_tag "application" %>
  </body>
</html>